# Generated by Django 5.0.2 on 2024-11-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images'),
        ),
    ]
